
version: '3.9'

services:
  superset:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: superset
    env_file:
      - ../.env
    ports:
      - '8088:8088'
    networks:
      - data_network

  trino:
    image: trinodb/trino:400
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino-conf:/etc/trino
    environment:
      JAVA_TOOL_OPTIONS: "-Duser.timezone=UTC"
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
    name: data_network
